uploads = []

[[generated]]
id = "gvFQ7BJ8ZfNTHv53kPkYB"
uri = "file://oolong-header.png"
type = "image"
title = "generated_image"

[[generated]]
id = "re1W9-rUQZCd6nCWldM89"
uri = "file://tea-img-puer.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ww6mA73cJ_r-B8B3XNjVq"
uri = "file://tea-img-oolong.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oWyyeAuOohuqOXIb8dsEC"
uri = "file://tea-img-green.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2_3SA_E2FEmOL7DarP2uP"
uri = "file://tea-img-white.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yYr2QtHjijvSi15B638rQ"
uri = "file://tea-img-yellow.png"
type = "image"
title = "generated_image"

[[generated]]
id = "C5lJf-vSoqwTH0eORx1yO"
uri = "file://tea-img-red.png"
type = "image"
title = "generated_image"

[[generated]]
id = "KkMetVp7nBw0bvR0iM7go"
uri = "file://tea-img-black.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nXfXEsVLp21mpaJUkFYIl"
uri = "file://tea-img-oolong-v1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JRjMDmqCCxDxofbHngjAQ"
uri = "file://tea-img-oolong-v2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DftMjiK44HmNLzamET7Oi"
uri = "file://tea-img-oolong-v3.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "w0VFch01s9iebcWrIoeP5"
uri = "file://chainan_2026-04-19_01-37-59.zip"
type = "unspecified"
title = "chainan_2026-04-19_01-37-59.zip"

[[outputs]]
id = "S3Qd_0HcUsY0yQcq_FeFK"
uri = "file://chainan_2026-04-21_01-44-39.zip"
type = "unspecified"
title = "chainan_2026-04-21_01-44-39.zip"

[[outputs]]
id = "yutoq_bqD7RwRKzajS_me"
uri = "file://tea-img-puer.png"
type = "image"
title = "Эталон — пуэр"

[[outputs]]
id = "aA7apEv4uvY8eFPuU387O"
uri = "file://tea-img-oolong.png"
type = "image"
title = "Улун — без шаров"

[[outputs]]
id = "CFvm9E2At0yiCrsdUpDAH"
uri = "file://tea-img-oolong-v1.png"
type = "image"
title = "Вариант 1"

[[outputs]]
id = "LWLmuoEM2Xqx2tzR-ly9Y"
uri = "file://tea-img-oolong-v2.png"
type = "image"
title = "Вариант 2"

[[outputs]]
id = "w70ZgzoiSxiADy2hetS_v"
uri = "file://tea-img-oolong-v3.png"
type = "image"
title = "Вариант 3"
